scsi: mpi3mr: Fix a format specifier
Fix the following compiler warning when building a 32-bit kernel:

./include/linux/kern_levels.h:5:25: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘unsigned int’ [-Werror=format=]
drivers/scsi/mpi3mr/mpi3mr_transport.c:1367:25: note: in expansion of macro ‘ioc_warn’
 1367 |                         ioc_warn(mrioc, "skipping port %u, max allowed value is %lu\n",
      |                         ^~~~~~~~

Cc: Tomas Henzl <thenzl@redhat.com>
Cc: Sathya Prakash Veerichetty <sathya.prakash@broadcom.com>
Fixes: 3668651def2c ("scsi: mpi3mr: Sanitise num_phys")
Signed-off-by: Bart Van Assche <bvanassche@acm.org>